### ISSUE TITLE
SOMEONE HELP ME PLEASE ... Internal server error When Access https://convertonlinefree.com

### ISSUE THREAD

**Issue by lukasreinhard** [VuongVu/word2pdf#6]
<!DOCTYPE html>
<html>
<head>
    <link rel="canonical" href="https://convertonlinefree.com/500.htm" />
    <title>Internal server error</title>
    <link rel="shortcut icon" href="convertonlinefree.ico" />
    <meta name="TITLE" content="Free online converter internal server error" />
    <meta charset="UTF-8" />
    <meta name="VW96.OBJECT TYPE" content="Document" />
    <meta name="RATING" content="General" />
    <meta name="ROBOTS" content="index,follow" />
    <meta name="REVISIT-AFTER" content="2 weeks" />
    <meta name="description" content="Free online document converter internal error page" />
    <meta name="keywords" content="internal,error" />

**Comment by pointnet** [comment]
Please check https://github.com/VuongVu/word2pdf/issues/2

**Comment by lukasreinhard** [comment]
Thanks Bro, Its solve now... (I use #7 )
