### ISSUE TITLE
V 1.0.13 It's not working

### ISSUE THREAD

**Issue by vipuldiwan** [VuongVu/word2pdf#8]
V 1.0.13 is not converting docx to pdf.

**Comment by pointnet** [comment]
Please check https://github.com/VuongVu/word2pdf/issues/2

**Comment by vipuldiwan** [comment]
Still have same issue.

**Comment by Ramprasathb** [comment]
Still facing the same issue

**Comment by khaledhublo** [comment]
This is unfortunate but the Owner of the package is web scrapping a website to do this, I spoke with the website owner and they're not in agreement, I wouldn't recommend using this package.
This one is a paying service for over 1000 docs. It's relatively cheap for around 9$ a month for 20K documents, We're using it in production in my company. And also, I'm the guy maintaining this thing.  
https://www.npmjs.com/package/iva-converter

There's a chat section on the website https://www.iva-docs.com
I'm there all the time. don't hesitate
